### ISSUE TITLE
Add config command to set Main Stream of Hikvision

### ISSUE THREAD

**Issue by jcmaslan** [CamioCam/rtsp#27] opened 2016-09-06 22:53 UTC
We need to modify the config commands to accept PUT payload like this for setting the Main Stream of a Hikvision DS-2CD2032-I.

```
PUT http://192.168.1.33/ISAPI/Streaming/channels/101
```

where the payload is:

``` xml
<?xml version="1.0" encoding="UTF-8"?><StreamingChannel xmlns="http://www.hikvision.com/ver20/XMLSchema" version="2.0">
<id>101</id>
<channelName>Camera 01</channelName>
<enabled>true</enabled>
<Transport>
<maxPacketSize>1000</maxPacketSize>
<ControlProtocolList>
<ControlProtocol>
<streamingTransport>RTSP</streamingTransport>
</ControlProtocol>
<ControlProtocol>
<streamingTransport>HTTP</streamingTransport>
</ControlProtocol>
<ControlProtocol>
<streamingTransport>SHTTP</streamingTransport>
</ControlProtocol>
</ControlProtocolList>
<Unicast>
<enabled>true</enabled>
<rtpTransportType>RTP/TCP</rtpTransportType>
</Unicast>

<Security>
<enabled>true</enabled>
</Security>
</Transport>
<Video>
<enabled>true</enabled>
<videoInputChannelID>1</videoInputChannelID>
<videoCodecType>H.264</videoCodecType>
<videoScanType>progressive</videoScanType>
<videoResolutionWidth>1280</videoResolutionWidth>
<videoResolutionHeight>720</videoResolutionHeight>
<videoQualityControlType>vbr</videoQualityControlType>

<fixedQuality>60</fixedQuality>
<vbrUpperCap>2048</vbrUpperCap>
<vbrLowerCap>32</vbrLowerCap>
<maxFrameRate>2000</maxFrameRate>

<snapShotImageType>JPEG</snapShotImageType>

<GovLength>50</GovLength>
<SVC>
<enabled>false</enabled>
</SVC>
<PacketType>PS</PacketType>
<PacketType>RTP</PacketType>

<H264Profile>Main</H264Profile></Video>
</StreamingChannel>
```

And the response is:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<ResponseStatus version="2.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
<requestURL>/ISAPI/Streaming/channels/101</requestURL>
<statusCode>1</statusCode>
<statusString>OK</statusString>
<subStatusCode>ok</subStatusCode>
</ResponseStatus>
```

This corresponds to the configuration page:
![screen shot 2016-09-06 at 3 52 10 pm](https://cloud.githubusercontent.com/assets/915853/18293807/f84da3b6-7449-11e6-82f1-d74d8d825082.png)

**Comment by jcmaslan** [comment] 2016-09-06 23:04
Specifically @jhallard, we need to modify this to accept a specification of a payload template so that we can supply the XML payload for the `PUT` command:
https://github.com/CamioCam/rtsp/tree/master/configs

**Comment by mdipierro** [comment] 2016-09-06 23:23
I can take this and to it today. I assume you want the command to take a general payload and return the response back to the server. The specifics of the payload would be set by the server. Correct? Synchronously or asynchronously?

**Comment by jcmaslan** [comment] 2016-09-07 00:03
I think it's adequate to recognize success with match on `regex_success`.
I'll open an issue in the firmware repo to finish discussing that implementation.

**Comment by jhallard** [comment] 2016-09-07 19:08
Just to be clear, should we add another column to the config.csv file that is like 'payload', and contains a link to a file that contains the XML payload to go with a PUT or POST request?

**Comment by jcmaslan** [comment] 2016-09-07 20:04
That sounds good to me.

**Comment by jhallard** [comment] 2016-09-08 18:02
Just to be clear, what should be templated in the XML? `videoResolutionwidth/videoResolutionHeight`? Also, should this only work with channel 01? When I try to PUT to `channel/102` or `channel/202` I always get errors, but PUT'ing this XML data to `channel/101` works just fine.

**Comment by jhallard** [comment] 2016-09-08 19:15
You were right about the error to channel 102 being caused by an invalid payload, here is the payload that works with channel 102. It's now in the repo as `/configs/hikvision_ds-2cd2032-I-stream_02.xml`

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<StreamingChannel version="2.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
    <id>102</id>
    <channelName>Camera 02</channelName>
    <enabled>true</enabled>
    <Transport>
        <maxPacketSize>1000</maxPacketSize>
        <ControlProtocolList>
            <ControlProtocol>
                <streamingTransport>RTSP</streamingTransport>
            </ControlProtocol>
            <ControlProtocol>
                <streamingTransport>HTTP</streamingTransport>
            </ControlProtocol>
            <ControlProtocol>
                <streamingTransport>SHTTP</streamingTransport>
            </ControlProtocol>
        </ControlProtocolList>
        <Unicast>
            <enabled>true</enabled>
            <rtpTransportType>RTP/TCP</rtpTransportType>
        </Unicast>
        <Multicast>
            <enabled>true</enabled>
            <destIPAddress>0.0.0.0</destIPAddress>
            <videoDestPortNo>8600</videoDestPortNo>
            <audioDestPortNo>8600</audioDestPortNo>
        </Multicast>
        <Security>
            <enabled>true</enabled>
        </Security>
    </Transport>
    <Video>
        <enabled>true</enabled>
        <videoInputChannelID>1</videoInputChannelID>
        <videoCodecType>H.264</videoCodecType>
        <videoScanType>progressive</videoScanType>
        <videoResolutionWidth>352</videoResolutionWidth>
        <videoResolutionHeight>240</videoResolutionHeight>
        <videoQualityControlType>VBR</videoQualityControlType>
        <constantBitRate>512</constantBitRate>
        <fixedQuality>60</fixedQuality>
        <vbrUpperCap>512</vbrUpperCap>
        <vbrLowerCap>32</vbrLowerCap>
        <maxFrameRate>3000</maxFrameRate>
        <keyFrameInterval>1666</keyFrameInterval>
        <snapShotImageType>JPEG</snapShotImageType>
        <H264Profile>Main</H264Profile>
        <GovLength>50</GovLength>
        <SVC>
            <enabled>false</enabled>
        </SVC>
        <PacketType>PS</PacketType>
        <PacketType>RTP</PacketType>
        <smoothing>50</smoothing>
    </Video>
</StreamingChannel>
```

**Comment by jhallard** [comment] 2016-09-09 19:50
This is done and has been tested manually with curl to confirm our xml data is correct. Now that it's merged I'm closing.

**Closed as completed by jhallard** 2016-09-09 19:50 UTC
Labels: enhancement
